"""drop spent_hours from tasks

Revision ID: 17abf1792deb
Revises: a8b9a591bc01
Create Date: 2026-08-16 13:27:16.311736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17abf1792deb'
down_revision = 'a8b9a591bc01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('spent_hours')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spent_hours', sa.FLOAT(), nullable=False))

    # ### end Alembic commands ###
