"""Initial migration: courses, tasks, subtasks

Revision ID: 19e248f918f9
Revises: 
Create Date: 2026-08-15 21:52:55.158394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19e248f918f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('HOMEWORK', 'EXAM', 'PROJECT', 'READING', 'PAPER', 'OTHER', name='tasktype'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('due_time', sa.Time(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='priority'), nullable=False),
    sa.Column('workload', sa.Enum('LIGHT', 'MODERATE', 'HEAVY', name='workload'), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'DONE', name='taskstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recurring', sa.Boolean(), nullable=False),
    sa.Column('reminder', sa.Enum('NONE', 'DAY_OF', 'ONE_DAY_BEFORE', 'TWO_DAYS_BEFORE', 'ONE_WEEK_BEFORE', name='reminderleadtime'), nullable=False),
    sa.Column('spent_hours', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subtasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=300), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subtasks')
    op.drop_table('tasks')
    op.drop_table('courses')
    # ### end Alembic commands ###
