"""Add settings table

Revision ID: 2850d476edad
Revises: 19e248f918f9
Create Date: 2026-08-15 22:24:42.840140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2850d476edad'
down_revision = '19e248f918f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('default_reminder', sa.Enum('NONE', 'DAY_OF', 'ONE_DAY_BEFORE', 'TWO_DAYS_BEFORE', 'ONE_WEEK_BEFORE', name='reminderleadtime'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
